syntax = "proto3";

package emailservice;

option go_package = "github.com/TheDurodola/go-email-service/src/config/emailservice";

service EmailService {
    rpc SendEmail (SendEmailRequest) returns (SendEmailResponse) {}
    rpc AddEmailTemplate (EmailTemplateRequest) returns (EmailTemplateResponse) {}
}


enum TemplateType {
  PLAIN_TEXT = 0;   
  HTML = 1;
}


message SendEmailRequest{
    string firstname = 1;
    string to = 2;
    string template_name = 3;
}

message SendEmailResponse {
    bool is_sent = 1;
}

message EmailTemplateRequest {
    string template_name = 1;
    TemplateType template_type = 2;
    string template_body = 3;
}

message EmailTemplateResponse {
    bool is_added = 1;
    string message = 2;
}
