// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/email/emailservice.proto

package emailservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplateType int32

const (
	TemplateType_STATIC  TemplateType = 0
	TemplateType_DYNAMIC TemplateType = 1
)

// Enum value maps for TemplateType.
var (
	TemplateType_name = map[int32]string{
		0: "STATIC",
		1: "DYNAMIC",
	}
	TemplateType_value = map[string]int32{
		"STATIC":  0,
		"DYNAMIC": 1,
	}
)

func (x TemplateType) Enum() *TemplateType {
	p := new(TemplateType)
	*p = x
	return p
}

func (x TemplateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_email_emailservice_proto_enumTypes[0].Descriptor()
}

func (TemplateType) Type() protoreflect.EnumType {
	return &file_proto_email_emailservice_proto_enumTypes[0]
}

func (x TemplateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateType.Descriptor instead.
func (TemplateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_email_emailservice_proto_rawDescGZIP(), []int{0}
}

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Firstname     string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TemplateName  string                 `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	AppName       string                 `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_proto_email_emailservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_emailservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_emailservice_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *SendEmailRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSent        bool                   `protobuf:"varint,1,opt,name=is_sent,json=isSent,proto3" json:"is_sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_proto_email_emailservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_emailservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_emailservice_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResponse) GetIsSent() bool {
	if x != nil {
		return x.IsSent
	}
	return false
}

type EmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateName  string                 `protobuf:"bytes,1,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	TemplateType  TemplateType           `protobuf:"varint,2,opt,name=template_type,json=templateType,proto3,enum=emailservice.TemplateType" json:"template_type,omitempty"`
	TemplateBody  string                 `protobuf:"bytes,3,opt,name=template_body,json=templateBody,proto3" json:"template_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailTemplateRequest) Reset() {
	*x = EmailTemplateRequest{}
	mi := &file_proto_email_emailservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTemplateRequest) ProtoMessage() {}

func (x *EmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_emailservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*EmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_emailservice_proto_rawDescGZIP(), []int{2}
}

func (x *EmailTemplateRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *EmailTemplateRequest) GetTemplateType() TemplateType {
	if x != nil {
		return x.TemplateType
	}
	return TemplateType_STATIC
}

func (x *EmailTemplateRequest) GetTemplateBody() string {
	if x != nil {
		return x.TemplateBody
	}
	return ""
}

type EmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdded       bool                   `protobuf:"varint,1,opt,name=is_added,json=isAdded,proto3" json:"is_added,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailTemplateResponse) Reset() {
	*x = EmailTemplateResponse{}
	mi := &file_proto_email_emailservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTemplateResponse) ProtoMessage() {}

func (x *EmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_emailservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*EmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_emailservice_proto_rawDescGZIP(), []int{3}
}

func (x *EmailTemplateResponse) GetIsAdded() bool {
	if x != nil {
		return x.IsAdded
	}
	return false
}

func (x *EmailTemplateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_email_emailservice_proto protoreflect.FileDescriptor

const file_proto_email_emailservice_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/email/emailservice.proto\x12\femailservice\"\x80\x01\n" +
	"\x10SendEmailRequest\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12\x19\n" +
	"\bapp_name\x18\x04 \x01(\tR\aappName\",\n" +
	"\x11SendEmailResponse\x12\x17\n" +
	"\ais_sent\x18\x01 \x01(\bR\x06isSent\"\xa1\x01\n" +
	"\x14EmailTemplateRequest\x12#\n" +
	"\rtemplate_name\x18\x01 \x01(\tR\ftemplateName\x12?\n" +
	"\rtemplate_type\x18\x02 \x01(\x0e2\x1a.emailservice.TemplateTypeR\ftemplateType\x12#\n" +
	"\rtemplate_body\x18\x03 \x01(\tR\ftemplateBody\"L\n" +
	"\x15EmailTemplateResponse\x12\x19\n" +
	"\bis_added\x18\x01 \x01(\bR\aisAdded\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*'\n" +
	"\fTemplateType\x12\n" +
	"\n" +
	"\x06STATIC\x10\x00\x12\v\n" +
	"\aDYNAMIC\x10\x012\xbd\x01\n" +
	"\fEmailService\x12N\n" +
	"\tSendEmail\x12\x1e.emailservice.SendEmailRequest\x1a\x1f.emailservice.SendEmailResponse\"\x00\x12]\n" +
	"\x10AddEmailTemplate\x12\".emailservice.EmailTemplateRequest\x1a#.emailservice.EmailTemplateResponse\"\x00BAZ?github.com/TheDurodola/go-email-service/src/config/emailserviceb\x06proto3"

var (
	file_proto_email_emailservice_proto_rawDescOnce sync.Once
	file_proto_email_emailservice_proto_rawDescData []byte
)

func file_proto_email_emailservice_proto_rawDescGZIP() []byte {
	file_proto_email_emailservice_proto_rawDescOnce.Do(func() {
		file_proto_email_emailservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_email_emailservice_proto_rawDesc), len(file_proto_email_emailservice_proto_rawDesc)))
	})
	return file_proto_email_emailservice_proto_rawDescData
}

var file_proto_email_emailservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_email_emailservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_email_emailservice_proto_goTypes = []any{
	(TemplateType)(0),             // 0: emailservice.TemplateType
	(*SendEmailRequest)(nil),      // 1: emailservice.SendEmailRequest
	(*SendEmailResponse)(nil),     // 2: emailservice.SendEmailResponse
	(*EmailTemplateRequest)(nil),  // 3: emailservice.EmailTemplateRequest
	(*EmailTemplateResponse)(nil), // 4: emailservice.EmailTemplateResponse
}
var file_proto_email_emailservice_proto_depIdxs = []int32{
	0, // 0: emailservice.EmailTemplateRequest.template_type:type_name -> emailservice.TemplateType
	1, // 1: emailservice.EmailService.SendEmail:input_type -> emailservice.SendEmailRequest
	3, // 2: emailservice.EmailService.AddEmailTemplate:input_type -> emailservice.EmailTemplateRequest
	2, // 3: emailservice.EmailService.SendEmail:output_type -> emailservice.SendEmailResponse
	4, // 4: emailservice.EmailService.AddEmailTemplate:output_type -> emailservice.EmailTemplateResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_email_emailservice_proto_init() }
func file_proto_email_emailservice_proto_init() {
	if File_proto_email_emailservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_email_emailservice_proto_rawDesc), len(file_proto_email_emailservice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_email_emailservice_proto_goTypes,
		DependencyIndexes: file_proto_email_emailservice_proto_depIdxs,
		EnumInfos:         file_proto_email_emailservice_proto_enumTypes,
		MessageInfos:      file_proto_email_emailservice_proto_msgTypes,
	}.Build()
	File_proto_email_emailservice_proto = out.File
	file_proto_email_emailservice_proto_goTypes = nil
	file_proto_email_emailservice_proto_depIdxs = nil
}
